---
dist: trusty
language: python
python: "2.7"

sudo: true

env:
  - lxd_container_alias: centos/7/amd64
  - lxd_container_alias: centos/6/amd64
  - lxd_container_alias: ubuntu/xenial/amd64
  - lxd_container_alias: ubuntu/trusty/amd64
  - lxd_container_alias: debian/stretch/amd64
  - lxd_container_alias: debian/jessie/amd64
  - lxd_container_alias: debian/wheezy/amd64

install:
  # Installing latest ansible
  - sudo -H pip install ansible
  # Cloning testing template
  - sudo mkdir /etc/ansible
  - sudo chown -R "${USER}:" /etc/ansible
  - git clone https://github.com/Nani-o/ansible-template-role-test /etc/ansible

script:
  # Run tests.
  - bash /etc/ansible/test.sh
