---
- name: Install requirements
  package:
    name: "{{ jackett_requirements }}"
    state: latest

- name: Get artifact url
  uri:
    url: https://github.com/Jackett/Jackett/releases/latest
  register: webpage

- name: Get actual url
  set_fact:
    jackett_release_url: "{{ webpage.url | replace('tag', 'download') }}/{{ jackett_release_file_name }}"

- name: Add service user
  user:
    name: "{{ jackett_user }}"
    state: present

- name: Download and untar binaries
  unarchive:
    remote_src: yes
    src: "{{ jackett_release_url }}"
    dest: /usr/local/bin
    owner: "{{ jackett_user }}"
  notify:
    - restart jackett

- name: Installing systemd service
  template:
    src: jackett.service.j2
    dest: /etc/systemd/system/jackett.service
    owner: root
    group: root
    mode: 0644
  notify:
    - systemd daemon-reload
    - restart jackett
